/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of ECLs.xs. Do not edit this file, edit ECLs.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "ECLs.xs"
#include <ecl/ecl.h>

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"


#define PACKAGE_LIST "Language::Lisp::ECLs::List"
#define PACKAGE_CODE "Language::Lisp::ECLs::Code"
#define PACKAGE_SYMBOL "Language::Lisp::ECLs::Symbol"
#define PACKAGE_STRING "Language::Lisp::ECLs::String"
#define PACKAGE_GENERIC "Language::Lisp::ECLs::Generic"
#define PACKAGE_PACKAGE "Language::Lisp::ECLs::Package"
#define PACKAGE_HASHTABLE "Language::Lisp::ECLs::HashTable"

static int boot_done = 0;
static cl_object current_package = 0;

/* the structure below is used to pass SvPV to LISP */
static struct ecl_base_string lisp_str = {
    t_base_string, 0, 0, 0,
    Cnil,
    0,
    0,
    0
};

static HV*
create_lisp_on_sv(SV *rsv, const char *pkg_name)
{
    char classname[200];
    SV *sv = SvRV(rsv);
    HV *phv;
    if (strchr(pkg_name,':')!=0) {
	strcpy(classname,pkg_name); /* if full name given, use it */
    } else {
	sprintf(classname, "Language::Lisp::ECLs::%s",pkg_name); /*otherwise ...*/
    }
    phv = gv_stashpv(classname,GV_ADD);
    sv_bless(rsv,phv);
    return phv;
}

static SV*
create_lisp_sv(const char *pkg_name, cl_object obj)
{
    SV *sv = newSVpv((char*)&obj,4);
    SV *rsv = newRV_noinc(sv); /* after this sv will have refcnt 1 (fortunately) */
    create_lisp_on_sv(rsv, pkg_name);
    return rsv;
}

static SV*
create_lisp_av(const char *pkg_name, cl_object obj)
{
    SV *sv = newSVpv((char*)&obj,4);
    AV *av = newAV();
    SV *rsv = newRV_noinc(sv); /* after this sv will have refcnt 1 (fortunately) */
    SV *rav = newRV_noinc(av); /* after this sv will have refcnt 1 (fortunately) */
    HV *phv = create_lisp_on_sv(rsv, pkg_name);
    /* have blessed reference, now TIE it! */
    sv_magic(rsv,phv,PERL_MAGIC_tied,0,0);
    return rav;
}

/* given blessed reference, which is actually pointer to cl_object,
 * return this as lisp object */
static cl_object
sv2cl_nocheck(SV *sv)
{
    cl_object clo;
    /* proper checks are not within scope of this fun */
    SV *sv_deref = SvRV(sv);
    memcpy(&clo,SvPV_nolen(sv_deref),4);
    return clo;
}

static cl_object
sv2cl(SV *sv)
{
    if (sv_isobject(sv)) {
	if (sv_isobject(sv) && sv_derived_from(sv, "Language::Lisp::ECLs")) {
	    cl_object clo;
	    SV *sv_deref = SvRV(sv);
	    memcpy(&clo,SvPV_nolen(sv_deref),4);
	    return clo;
	} else {
	    SV *sv_deref = SvRV(sv);
	    fprintf(stderr,"sv2cl: str=%s;\n",SvPV_nolen(sv_deref));
	    croak("sv2cl: passed not a subclass of Language::Lisp::ECLs");
	}
    } else if (SvIOK(sv)) {
	int iv = SvIV(sv); 
        /* fprintf(stderr,"SvIOK, %d, good!\n",iv); */
	return ecl_make_integer(iv);
    } else if (SvPOK(sv)) {
	int len;
        char *str = SvPV(sv,len);
        cl_object x = cl_alloc_simple_base_string(len);
        /* fprintf(stderr,"SvPOK, %s, good!\n",str); */
        memcpy(x->base_string.self, str, len);
        /*x->base_string.self[len] = 0;*/ // TODO freeing of this stuff
	return x;
    } else {
	fprintf(stderr,"sv2cl: str=%s;\n",SvPV_nolen(sv));
	croak("sv2cl: passed not a subclass of Language::Lisp::ECLs, not string and not int");
    }
}

static SV *
cl2sv(cl_object clo)
{
    SV *sv;
    switch (type_of(clo)) {
    case t_list:
	sv = create_lisp_sv(PACKAGE_LIST, clo);
	break;
    case t_fixnum:
	sv = newSViv(fix(clo));
	break;
    case t_base_string:
	sv = newSVpv(clo->base_string.self,clo->base_string.fillp);
	break;
#ifdef ECL_UNICODE
    case t_string:
	fprintf(stderr,"wtf - t_string(%d)\n",clo->string.fillp);
	sv = newSVpv(clo->string.self,clo->string.fillp);
	break;
#endif
    case t_package:
	sv = create_lisp_sv(PACKAGE_PACKAGE, clo);
	break;
    case t_hashtable:
	sv = create_lisp_sv(PACKAGE_HASHTABLE, clo);
	break;
    case t_bytecodes:
	sv = create_lisp_sv(PACKAGE_CODE, clo);
	break;
    case t_symbol:
	    /*
	n = ecl_symbol_name(clo);
	p = ecl_symbol_package(clo);
	fprintf(stderr,"n-type %d, n=%s p-type %d\n",
	    type_of(n),
	    (type_of(n)==t_base_string?n->base_string.self:"??"),
	    type_of(p));
	    */
	sv = create_lisp_sv(PACKAGE_SYMBOL, clo);
	break;
    default:
	fprintf(stderr,"type %d not impl!\n",type_of(clo));
	sv = create_lisp_sv(PACKAGE_GENERIC, clo);
	break;
    }
    return sv;
}

static void
free_cl(SV *sv)
{
    cl_object o = sv2cl(sv);
    if (type_of(o) == t_base_string) {
	fprintf(stderr,"freeing a base_string\n");
        GC_free(o->base_string.self);
    } else {
	fprintf(stderr,"free of type %d not impl!\n",type_of(o));
    }
}

#line 180 "ECLs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 324 "ECLs.c"

XS_EUPXS(XS_Language__Lisp__ECLs__List_FETCH); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__List_FETCH)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "this, n");
    {
	SV *	this = ST(0)
;
	int	n = (int)SvIV(ST(1))
;
#line 177 "ECLs.xs"
        cl_object clo = sv2cl(this);
#line 339 "ECLs.c"
	SV *	RETVAL;
#line 179 "ECLs.xs"
	/* get n-th item, obviously... */
	/* fprintf(stderr,"FETCH(this) n=%d, len=%d\n", n, len); */
	if (type_of(clo) == t_list) {
	    cl_object o;
	    if (n<0) {
		int len = fix(cl_list_length(clo));
	        n = len+n;
	    }
	    if (n<0) {
		RETVAL = &PL_sv_undef;
	    }
	    o = ecl_nth(n,clo);
	    if (o==Cnil || o==OBJNULL) {
		RETVAL = &PL_sv_undef;
	    } else {
		RETVAL = cl2sv(o);
	    }
	} else {
	    croak("weird lisp object, must be t_list");
	}
#line 362 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__List_STORE); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__List_STORE)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "this, n, val");
    {
	SV *	this = ST(0)
;
	int	n = (int)SvIV(ST(1))
;
	SV *	val = ST(2)
;
#line 208 "ECLs.xs"
        cl_object clo = sv2cl(this);
        cl_object clval = sv2cl(val);
	int len = fix(cl_list_length(clo));
#line 387 "ECLs.c"
#line 212 "ECLs.xs"
	/* set n-th item, NOT IMPLEMENTED... */
	if (type_of(clo) == t_list) {
	    if (n<0) {
	        n = len+n;
	    }
	    if (n<0) {
		return;
	    }
	    if (n>=len || n<0) {
	    }
	    croak("STORE not here");
	} else {
	    croak("weird lisp object, must be t_list");
	}
#line 403 "ECLs.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Language__Lisp__ECLs__List_FETCHSIZE); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__List_FETCHSIZE)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "this");
    {
	SV *	this = ST(0)
;
#line 231 "ECLs.xs"
        cl_object clo = sv2cl(this);
	int len = fix(cl_list_length(clo));
#line 421 "ECLs.c"
	int	RETVAL;
	dXSTARG;
#line 234 "ECLs.xs"
	/* get number of items, obviously... */
	if (type_of(clo) == t_list) {
	    RETVAL = len;
	} else {
	    croak("weird lisp object, must be t_list");
	}
#line 431 "ECLs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__List_TIEARRAY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__List_TIEARRAY)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "classname, obj");
    {
	SV *	classname = ST(0)
;
	SV *	obj = ST(1)
;
#line 248 "ECLs.xs"
	HV *phv = gv_stashsv(classname,GV_ADD);
#line 451 "ECLs.c"
	SV *	RETVAL;
#line 250 "ECLs.xs"
        if (sv_isobject(obj)) {
	    /* if its object then blessing could lose
	     * refcount on it ?? */
	    SvREFCNT_inc(obj);
	    RETVAL = sv_bless(obj,phv);
	    /* SvREFCNT_dec(obj); this not work */
	} else {
	    RETVAL = sv_bless(obj,phv);
	}
#line 463 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__Package_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__Package_stringify)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "clsv");
    {
	SV *	clsv = ST(0)
;
#line 268 "ECLs.xs"
        cl_object clo, np;
#line 482 "ECLs.c"
	SV *	RETVAL;
#line 270 "ECLs.xs"
        clo = sv2cl(clsv);
	if (type_of(clo) == t_package) {
	    np = cl_package_name(clo);
	    RETVAL = newSVpvf("#<PACKAGE %s>",
		(type_of(np)==t_base_string?np->base_string.self:"??")
	      );
	} else {
	    croak("can not stringify non-t_package within ...::Package package");
	}
#line 494 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__Symbol_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__Symbol_stringify)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "clsv");
    {
	SV *	clsv = ST(0)
;
#line 288 "ECLs.xs"
        cl_object clo, n, p, np;
#line 513 "ECLs.c"
	SV *	RETVAL;
#line 290 "ECLs.xs"
        clo = sv2cl(clsv);
	if (type_of(clo) == t_symbol) {
	    n = ecl_symbol_name(clo);
	    p = ecl_symbol_package(clo);
	    np = cl_package_name(p);
	    RETVAL = newSVpvf("#<SYMBOL %s::%s>",
		(type_of(np)==t_base_string?np->base_string.self:"??"),
		(type_of(n)==t_base_string?n->base_string.self:"??")
	      );
	} else {
	    croak("can not stringify non-t_symbol within ...::Symbol package");
	}
#line 528 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_stringify)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "clsv");
    {
	SV *	clsv = ST(0)
;
#line 311 "ECLs.xs"
        cl_object clo, n, p, np;
#line 547 "ECLs.c"
	SV *	RETVAL;
#line 313 "ECLs.xs"
        clo = sv2cl(clsv);
	if (type_of(clo) == t_hashtable) {
	    RETVAL = newSVpvf("#S<HASH-TABLE>");
	} else {
	    croak("can not stringify non-t_hashtable within ...::HashTable package");
	}
#line 556 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_EXISTS); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_EXISTS)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "this, key");
    {
	SV *	this = ST(0)
;
	SV *	key = ST(1)
;
#line 327 "ECLs.xs"
        cl_object clo = sv2cl(this);
        cl_object k = sv2cl(key);
	struct ecl_hashtable_entry *he;
#line 579 "ECLs.c"
	int	RETVAL;
	dXSTARG;
#line 331 "ECLs.xs"
	/* get 'key' item, obviously... */
	/* fprintf(stderr,"FETCH(this) key=%s\n", n, len); */
	if (type_of(clo) == t_hashtable) {
	    he = ecl_search_hash(k,clo);
	    if (he==Cnil || he==OBJNULL) {
		RETVAL = 0;
	    } else {
		RETVAL = 1;
	    }
	} else {
	    croak("weird lisp object, must be t_hashtable");
	}
#line 595 "ECLs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_FETCH); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_FETCH)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "this, key");
    {
	SV *	this = ST(0)
;
	SV *	key = ST(1)
;
#line 351 "ECLs.xs"
        cl_object clo = sv2cl(this);
        cl_object k = sv2cl(key);
#line 616 "ECLs.c"
	SV *	RETVAL;
#line 354 "ECLs.xs"
	/* get 'key' item, obviously... */
	fprintf(stderr,"FETCH(this) key=%s\n", SvPV_nolen(key));
	if (type_of(clo) == t_hashtable) {
	    cl_object o = ecl_gethash(k,clo);
	    fprintf(stderr," o=%08X\n", o);
	    if (o==Cnil || o==OBJNULL) {
		RETVAL = &PL_sv_undef;
	    } else {
		RETVAL = cl2sv(o);
	    }
	} else {
	    croak("weird lisp object, must be t_hashtable");
	}
#line 632 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_STORE); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_STORE)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "this, key, val");
    {
	SV *	this = ST(0)
;
	SV *	key = ST(1)
;
	SV *	val = ST(2)
;
#line 376 "ECLs.xs"
        cl_object clo = sv2cl(this);
        cl_object clval = sv2cl(val);
        cl_object k = sv2cl(key);
#line 657 "ECLs.c"
#line 380 "ECLs.xs"
	/* store item */
	fprintf(stderr,"STORE(this) key=%s\n", SvPV_nolen(key));
	fprintf(stderr,"            val=%s\n", SvPV_nolen(val));
	if (type_of(clo) == t_hashtable) {
	    ecl_sethash(k,clo,clval);
	} else {
	    croak("weird lisp object, must be t_hashtable");
	}
#line 667 "ECLs.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_TIEHASH); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__HashTable_TIEHASH)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "classname, obj");
    {
	SV *	classname = ST(0)
;
	SV *	obj = ST(1)
;
#line 394 "ECLs.xs"
	HV *phv = gv_stashsv(classname,GV_ADD);
#line 686 "ECLs.c"
	SV *	RETVAL;
#line 396 "ECLs.xs"
        if (sv_isobject(obj)) {
	    /* if its object then blessing could lose
	     * refcount on it ?? */
	    SvREFCNT_inc(obj);
	    RETVAL = sv_bless(obj,phv);
	    /* SvREFCNT_dec(obj); this not work */
	} else {
	    RETVAL = sv_bless(obj,phv);
	}
#line 698 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__Code_funcall); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__Code_funcall)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "self, ...");
    {
	SV *	self = ST(0)
;
#line 414 "ECLs.xs"
	cl_object def = sv2cl(self);
	cl_object res, args[10];
	int items1 = items;
#line 719 "ECLs.c"
	SV *	RETVAL;
#line 418 "ECLs.xs"
        switch (items1) {
	case 10:
	    args[8] = sv2cl(ST(9));
	    args[7] = sv2cl(ST(8));
	    args[6] = sv2cl(ST(7));
	    args[5] = sv2cl(ST(6));
	    args[4] = sv2cl(ST(5));
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8]);
	    RETVAL = cl2sv(res);
	    break;
	case 9:
	    args[7] = sv2cl(ST(8));
	    args[6] = sv2cl(ST(7));
	    args[5] = sv2cl(ST(6));
	    args[4] = sv2cl(ST(5));
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7]);
	    RETVAL = cl2sv(res);
	    break;
	case 8:
	    args[6] = sv2cl(ST(7));
	    args[5] = sv2cl(ST(6));
	    args[4] = sv2cl(ST(5));
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6]);
	    RETVAL = cl2sv(res);
	    break;
	case 7:
	    args[5] = sv2cl(ST(6));
	    args[4] = sv2cl(ST(5));
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5]);
	    RETVAL = cl2sv(res);
	    break;
	case 6:
	    args[4] = sv2cl(ST(5));
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4]);
	    RETVAL = cl2sv(res);
	    break;
	case 5:
	    args[3] = sv2cl(ST(4));
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3]);
	    RETVAL = cl2sv(res);
	    break;
	case 4:
	    args[2] = sv2cl(ST(3));
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1],args[2]);
	    RETVAL = cl2sv(res);
	    break;
	case 3:
	    args[1] = sv2cl(ST(2));
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0],args[1]);
	    RETVAL = cl2sv(res);
	    break;
	case 2:
	    args[0] = sv2cl(ST(1));
	    res = cl_funcall(items1,def,args[0]);
	    RETVAL = cl2sv(res);
	    break;
	case 1:
	    res = cl_funcall(items1,def);
	    RETVAL = cl2sv(res);
	    break;
	default:
	    fprintf(stderr, "items1=%d not supported\n",items1);
	    croak("items %d not supported - wtf");
	}
#line 812 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__String_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__String_stringify)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "clsv");
    {
	SV *	clsv = ST(0)
;
#line 517 "ECLs.xs"
        cl_object clo, n, p, np;
#line 831 "ECLs.c"
	SV *	RETVAL;
#line 519 "ECLs.xs"
        clo = sv2cl(clsv);
	if (type_of(clo) == t_base_string) {
	    RETVAL = newSVpv(clo->base_string.self,clo->base_string.fillp);
	} else {
	    croak("can not stringify non-t_base_string within ...::String package");
	}
#line 840 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__Generic_stringify); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__Generic_stringify)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "clsv");
    {
	SV *	clsv = ST(0)
;
#line 534 "ECLs.xs"
	char *types[] = {
	"t_start",
	"t_list",
	"t_character",
	"t_fixnum",
#ifdef ECL_SHORT_FLOAT
	"t_shortfloat",
#endif
	"t_bignum",
	"t_ratio",
	"t_singlefloat",
	"t_doublefloat",
#ifdef ECL_LONG_FLOAT
	"t_longfloat",
#endif
	"t_complex",
	"t_symbol",
	"t_package",
	"t_hashtable",
	"t_array",
	"t_vector",
#ifdef ECL_UNICODE
	"t_string",
#endif
	"t_base_string",
	"t_bitvector",
	"t_stream",
	"t_random",
	"t_readtable",
	"t_pathname",
	"t_bytecodes",
	"t_cfun",
	"t_cclosure",
#ifdef CLOS
	"t_instance",
#else
	"t_structure",
#endif /* CLOS */
#ifdef ECL_THREADS
	"t_process",
	"t_lock",
	"t_condition_variable",
#endif
	"t_codeblock",
	"t_foreign",
	"t_frame",
	"t_end",
	"t_other",
	"t_contiguous"
	    /*FREE = 127 */      /*  free object  */
	};
	int t;
	char *h;
	cl_object o = sv2cl(clsv);
#line 912 "ECLs.c"
	SV *	RETVAL;
#line 589 "ECLs.xs"
	t = type_of(o);
	if (t==127) {h="FREE";}
	else {h=types[t];}
	RETVAL = newSVpvf("can not stringify %s within ...::Generic package", h);
#line 919 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs_cl_boot); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs_cl_boot)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 601 "ECLs.xs"
        char *argv1[] = {""};
#line 936 "ECLs.c"
	int	RETVAL;
	dXSTARG;
#line 603 "ECLs.xs"
	//argc, argv TODO int argc
	//argc, argv TODO char **argv
        RETVAL = cl_boot(0,argv1);
	current_package = ecl_current_package();
	boot_done = 1;
#line 945 "ECLs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs_cl_shutdown); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs_cl_shutdown)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 614 "ECLs.xs"
        cl_shutdown();
#line 961 "ECLs.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Language__Lisp__ECLs__eval_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__eval_string)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "s");
    {
	char *	s = (char *)SvPV_nolen(ST(0))
;
#line 620 "ECLs.xs"
	cl_object def;
	cl_object n, p;
	cl_object res;
#line 980 "ECLs.c"
	SV *	RETVAL;
#line 624 "ECLs.xs"
	//if (!boot_done)
	//    XS_Language__Lisp__ECL_cl_boot(aTHX);
        def = c_string_to_object(s);
	res = si_safe_eval(3,def,Cnil,OBJNULL);
	/* destroy def (not work!!! TODO) */
	/* cl_dealloc(def->base_string.self); */
	/* def->base_string.self = 0; */
	/* cl_dealloc(def); */
	/* (check for memory leaks?) */
	RETVAL = (res?cl2sv(res):&PL_sv_undef);
#line 993 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__eval); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__eval)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "lispobj");
    {
	SV *	lispobj = ST(0)
;
#line 642 "ECLs.xs"
	cl_object def = sv2cl(lispobj);
	cl_object res;
#line 1013 "ECLs.c"
	SV *	RETVAL;
#line 645 "ECLs.xs"
	/* res = cl_eval(def); */
	res = si_safe_eval(3,def,Cnil,OBJNULL);
	RETVAL = (res?cl2sv(res):&PL_sv_undef);
#line 1019 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs_funcall); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs_funcall)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "self, lispobj, ...");
    {
	SV *	self = ST(0)
;
	SV *	lispobj = ST(1)
;
#line 656 "ECLs.xs"
	cl_object def = sv2cl(lispobj);
	cl_object res, args[10];
	int items1 = items-1;
#line 1042 "ECLs.c"
	SV *	RETVAL;
#line 660 "ECLs.xs"
        switch (items1) {
	case 10:
	    args[8] = sv2cl(ST(10));
	    args[7] = sv2cl(ST(9));
	    args[6] = sv2cl(ST(8));
	    args[5] = sv2cl(ST(7));
	    args[4] = sv2cl(ST(6));
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8]);
	    RETVAL = cl2sv(res);
	    break;
	case 9:
	    args[7] = sv2cl(ST(9));
	    args[6] = sv2cl(ST(8));
	    args[5] = sv2cl(ST(7));
	    args[4] = sv2cl(ST(6));
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7]);
	    RETVAL = cl2sv(res);
	    break;
	case 8:
	    args[6] = sv2cl(ST(8));
	    args[5] = sv2cl(ST(7));
	    args[4] = sv2cl(ST(6));
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5],args[6]);
	    RETVAL = cl2sv(res);
	    break;
	case 7:
	    args[5] = sv2cl(ST(7));
	    args[4] = sv2cl(ST(6));
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4],args[5]);
	    RETVAL = cl2sv(res);
	    break;
	case 6:
	    args[4] = sv2cl(ST(6));
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3],args[4]);
	    RETVAL = cl2sv(res);
	    break;
	case 5:
	    args[3] = sv2cl(ST(5));
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2],args[3]);
	    RETVAL = cl2sv(res);
	    break;
	case 4:
	    args[2] = sv2cl(ST(4));
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1],args[2]);
	    RETVAL = cl2sv(res);
	    break;
	case 3:
	    args[1] = sv2cl(ST(3));
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0],args[1]);
	    RETVAL = cl2sv(res);
	    break;
	case 2:
	    args[0] = sv2cl(ST(2));
	    res = cl_funcall(items1,def,args[0]);
	    RETVAL = cl2sv(res);
	    break;
	case 1:
	    res = cl_funcall(items1,def);
	    RETVAL = cl2sv(res);
	    break;
	default:
	    fprintf(stderr, "items=%d not supported\n",items);
	    croak("nitems %d not supported - wtf");
	}
#line 1135 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs__search_lisp_function); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs__search_lisp_function)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fname");
    {
	SV *	fname = ST(0)
;
#line 758 "ECLs.xs"
        int len, intern = 0;
        cl_object fun;
        cl_object sym;
#line 1156 "ECLs.c"
	SV *	RETVAL;
#line 762 "ECLs.xs"
	lisp_str.self = SvPV(fname,len);
	lisp_str.dim = len;
	lisp_str.fillp = len;
	sym = ecl_find_symbol((cl_object)&lisp_str, current_package, &intern);
        fun = ecl_fdefinition(sym);
	if (fun==OBJNULL || fun==Cnil) {
	    /* fprintf(stderr,"(fun==OBJNULL) %08X\n", fun); */
	    RETVAL = &PL_sv_undef;
	} else {
	    /* found function definition, so blessed object to ...::Code package
	     * is returned */
	    RETVAL = create_lisp_sv(PACKAGE_CODE,fun);
	}
#line 1172 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Language__Lisp__ECLs_create_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Language__Lisp__ECLs_create_string)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    {
	SV *	sv = ST(0)
;
#line 783 "ECLs.xs"
        int len;
	char *str;
        cl_object x;
#line 1193 "ECLs.c"
	SV *	RETVAL;
#line 787 "ECLs.xs"
        str = SvPV(sv,len);
        x = cl_alloc_simple_base_string(len);
        memcpy(x->base_string.self, str, len);
        /* x->base_string.self[len] = 0; */
	RETVAL = create_lisp_sv(PACKAGE_STRING,x);
#line 1201 "ECLs.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Language__Lisp__ECLs); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Language__Lisp__ECLs)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Language::Lisp::ECLs::List::FETCH", XS_Language__Lisp__ECLs__List_FETCH);
        newXS_deffile("Language::Lisp::ECLs::List::STORE", XS_Language__Lisp__ECLs__List_STORE);
        newXS_deffile("Language::Lisp::ECLs::List::FETCHSIZE", XS_Language__Lisp__ECLs__List_FETCHSIZE);
        newXS_deffile("Language::Lisp::ECLs::List::TIEARRAY", XS_Language__Lisp__ECLs__List_TIEARRAY);
        newXS_deffile("Language::Lisp::ECLs::Package::stringify", XS_Language__Lisp__ECLs__Package_stringify);
        newXS_deffile("Language::Lisp::ECLs::Symbol::stringify", XS_Language__Lisp__ECLs__Symbol_stringify);
        newXS_deffile("Language::Lisp::ECLs::HashTable::stringify", XS_Language__Lisp__ECLs__HashTable_stringify);
        newXS_deffile("Language::Lisp::ECLs::HashTable::EXISTS", XS_Language__Lisp__ECLs__HashTable_EXISTS);
        newXS_deffile("Language::Lisp::ECLs::HashTable::FETCH", XS_Language__Lisp__ECLs__HashTable_FETCH);
        newXS_deffile("Language::Lisp::ECLs::HashTable::STORE", XS_Language__Lisp__ECLs__HashTable_STORE);
        newXS_deffile("Language::Lisp::ECLs::HashTable::TIEHASH", XS_Language__Lisp__ECLs__HashTable_TIEHASH);
        newXS_deffile("Language::Lisp::ECLs::Code::funcall", XS_Language__Lisp__ECLs__Code_funcall);
        newXS_deffile("Language::Lisp::ECLs::String::stringify", XS_Language__Lisp__ECLs__String_stringify);
        newXS_deffile("Language::Lisp::ECLs::Generic::stringify", XS_Language__Lisp__ECLs__Generic_stringify);
        newXS_deffile("Language::Lisp::ECLs::cl_boot", XS_Language__Lisp__ECLs_cl_boot);
        newXS_deffile("Language::Lisp::ECLs::cl_shutdown", XS_Language__Lisp__ECLs_cl_shutdown);
        newXS_deffile("Language::Lisp::ECLs::_eval_string", XS_Language__Lisp__ECLs__eval_string);
        newXS_deffile("Language::Lisp::ECLs::_eval", XS_Language__Lisp__ECLs__eval);
        newXS_deffile("Language::Lisp::ECLs::funcall", XS_Language__Lisp__ECLs_funcall);
        newXS_deffile("Language::Lisp::ECLs::_search_lisp_function", XS_Language__Lisp__ECLs__search_lisp_function);
        newXS_deffile("Language::Lisp::ECLs::create_string", XS_Language__Lisp__ECLs_create_string);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

