--- #YAML:1.0
name:                ecl
version:             0.61
abstract:            Perl extension for ECL lisp
license:             artistic
author:              
    - Vadim Konovalov <vkon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
